var gapi=window.gapi=window.gapi||{};gapi._bs=new Date().getTime();(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g=this||self,h=function(a){return a};/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
var m=window,n=document,aa=m.location,ba=function(){},ca=/\[native code\]/,q=function(a,b,c){return a[b]=a[b]||c},da=function(a){a=a.sort();for(var b=[],c=void 0,d=0;d<a.length;d++){var e="a[d];e!=c&&b.push(e);c=e}return" b},v="function(){var" a;if((a="Object.create)&&ca.test(a))a=a(null);else{a={};for(var" b in a)a[b]="void" 0}return a},x="q(m,"gapi",{});var" c;c="q(m,"___jsl",v());q(C,"I",0);q(C,"hel",10);var" d="function(){var" a="aa.href;if(C.dpo)var" c="/([#].*&|[#])jsh=([^&#]*)/g,d=/([?#].*&|[?#])jsh=([^&#]*)/g;if(a=a&&(c.exec(a)||d.exec(a)))try{b=decodeURIComponent(a[2])}catch(e){}}return" b},fa="function(a){var" for(var q(q(c,"h",v()),a,v())};var f="q(C,"perf",v()),G=q(F,"g",v()),ha=q(F,"i",v());q(F,"r",[]);v();v();var" h="function(a,b,c){var" d?d(a,b,c):d.push([a,b,c])},l="function(a,b,c){b&&0<b.length&&(b=K(b),c&&0<c.length&&(b+="___"+K(c)),28<b.length&&(b=b.substr(0,28)+(b.length-28)),c=b,b=q(ha,"_p",v()),q(b,c,v())[a]=(new" date).gettime(),h(a,"_p",c))},k="function(a){return" a.join("__").replace( \. g,"_").replace( \- , g,"_")};var m="v(),N=[],Q=function(a){throw" error("bad hint"+(a?": "+a:""));};n.push(["jsl",function(a){for(var a)if(object.prototype.hasownproperty.call(a,b)){var c?c[b]="q(C,b,[]).concat(c):q(C,b,c)}if(b=a.u)a=q(C,"us",[]),a.push(b),(b=/^https:(.*)$/.exec(b))&&a.push("http:"+b[1])}]);var" ia="/^(\/[a-zA-Z0-9_\-]+)+$/,R=[/\/amp\//,/\/amp$/,/^\/amp$/],ja=/^[a-zA-Z0-9\-_\.,!]+$/,ka=/^gapi\.loaded_[0-9]+$/,la=/^[a-zA-Z0-9,._-]+$/,pa=function(a,b,c,d){var" hint processor for: "+f);k||q("failed to generate load url");b="k;c=b.match(ma);(d=b.match(na))&&1===d.length&&oa.test(b)&&c&&1===c.length||Q("failed" sanity: "+a);return k},ra="function(a,b,c,d){a=qa(a);ka.test(c)||Q("invalid_callback");b=S(b);d=d&&d.length?S(d):null;var" encodeuricomponent(f).replace( %2c g,",")};return[encodeuricomponent(a.pathprefix).replace( g,",").replace( %2f g," ")," k=",e(a.version)," exm="+e(d):" "," rt="j/sv=1/d=1/ed=1",a.g?"/am="+e(a.g):"",a.i?"/rs="+e(a.i):"",a.j?"/t="+e(a.j):"","/cb=",e(c)].join("")},qa=function(a){"/"!==a.charAt(0)&&Q("relative" path");for(var directory");else if(0<a.indexof("=")){b.unshift(a);
break}c.push(a)}a={};for(var d=0,e=b.length;d<e;++d){var f=b[d].split(" ="),l="decodeURIComponent(f[0]),k=decodeURIComponent(f[1]);2==f.length&&l&&k&&(a[l]=a[l]||k)}b="/"+c.join("/");ia.test(b)||Q("invalid_prefix");c=0;for(d=R.length;c<d;++c)R[c].test(b)&&Q("invalid_prefix");c=T(a,"k",!0);d=T(a,"am");e=T(a,"rs");a=T(a,"t");return{pathPrefix:b,version:c,g:d,i:e,j:a}},S=function(a){for(var" b.join(",")}, t="function(a,b,c){a=a[b];!a&&c&&Q("missing:" "+b);if(a){if(ja.test(a))return a;q("invalid: "+b)}return null},oa="/^https?:\/\/[a-z0-9_.-]+\.google(rs)?\.com(:\d+)?\/[a-zA-Z0-9_.,!=\-\/]+$/,na=/\/cb=/g,ma=/\/\//g,sa=function(){var" hint");return a};m.m="function(a,b,c,d){(a=a[0])||Q("missing_hint");return"https://apis.google.com"+ra(a,b,c,d)};var" u="decodeURI("%73cript"),V=/^[-+_0-9\/A-Za-z]+={0,2}$/,W=function(a,b){for(var" a;f="-1}f=0">f}f&&c.push(e)}return c},X=function(){var a=C.nonce;return void 0!==a?a&&a===String(a)&&a.match(V)?a:C.nonce=null:n.querySelector?(a=n.querySelector("script[nonce]"))?(a=a.nonce||a.getAttribute("nonce")||"",a&&a===String(a)&&a.match(V)?C.nonce=a:C.nonce=null):null:null},ua=function(a){if("loading"!=n.readyState)ta(a);
else{var b=X(),c="";null!==b&&(c=' nonce="'+b+'"');a="<"+U+' src="'+encodeURI(a)+'" '+c+">";n.write(Y?Y.createHTML(a):a)}},ta=function(a){var b=n.createElement(U);b.setAttribute("src",Y?Y.createScriptURL(a):a);a=X();null!==a&&b.setAttribute("nonce",a);b.async="true";(a=n.getElementsByTagName(U)[0])?a.parentNode.insertBefore(b,a):(n.head||n.body||n.documentElement).appendChild(b)},va=function(a,b){var c=b&&b._c;if(c)for(var d=0;d</"+U+'></a.length;d++){var>